#!/usr/bin/env python2.py

for i in range(10):
  print i,
print

print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  Absente       |  Mee           |  302740        |  8             |'
print '|  Burbple       |  Durple        |  124967        |  7             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  See           |  Mee           |  302740        |  1             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Miggh         |  Tyfine        |  124967        |  2             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  Absente       |  Mee           |  302740        |  8             |'
print '|  Burbple       |  Durple        |  124967        |  7             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  See           |  Mee           |  302740        |  1             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Miggh         |  Tyfine        |  124967        |  2             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  302740        |  8             |'
print '|  Burbple       |  Durple        |  124967        |  7             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  See           |  Mee           |  302740        |  1             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Miggh         |  Tyfine        |  124967        |  2             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  302740        |  8             |'
print '|  Burbple       |  Durple        |  124967        |  7             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  Henry         |  Groth         |  302740        |  1             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Miggh         |  Tyfine        |  124967        |  2             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  302740        |  8             |'
print '|  Burbple       |  Durple        |  124967        |  7             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  Henry         |  Groth         |  3994542       |  8             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Miggh         |  Tyfine        |  124967        |  2             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  302740        |  8             |'
print '|  Burbple       |  Durple        |  124967        |  7             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  Henry         |  Groth         |  3994542       |  9             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Miggh         |  Tyfine        |  124967        |  2             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  302740        |  8             |'
print '|  Job           |  Less          |  124967        |  7             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  Henry         |  Groth         |  3994542       |  9             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Job           |  Less          |  124967        |  2             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  302740        |  8             |'
print '|  Testme        |  Hesty         |  124967        |  5             |'
print '|  Hes           |  ABob          |  8675309       |  2             |'
print '|  Henry         |  Groth         |  3994542       |  9             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Testme        |  Hesty         |  124967        |  5             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  911           |  8             |'
print '|  Testme        |  Hesty         |  911           |  5             |'
print '|  Hes           |  ABob          |  911           |  2             |'
print '|  Henry         |  Groth         |  911           |  9             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Testme        |  Hesty         |  911           |  5             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  Lake          |  Travis        |  911           |  1             |'
print '|  PopBob        |  Bopey         |  911           |  8             |'
print '|  Testme        |  Hesty         |  911           |  5             |'
print '|  Hes           |  ABob          |  911           |  2             |'
print '|  Henry         |  Groth         |  911           |  9             |'
print '|  Jose          |  Nosey         |  911           |  2             |'
print '|  Testme        |  Hesty         |  911           |  5             |'
print '|--------------------------------------------------------------------'
print 'new_Customers:'
print '|--------------------------------------------------------------------'
print '|  name          |  last          |  phone         |  birthday      |'
print '|--------------------------------------------------------------------'
print '|  oCond         |  Iven          |  9343          |  6             |'
print '|  oCond         |  Iven          |  9343          |  6             |'
print '|  oCond         |  Iven          |  9343          |  6             |'
print '|  oCond         |  Iven          |  9343          |  6             |'
print '|  oCond         |  Iven          |  9343          |  6             |'
print '|  oCond         |  Iven          |  9343          |  6             |'
print '|  oCond         |  Iven          |  9343          |  6             |'
print '|--------------------------------------------------------------------'

